// Original hanging-sakura painting. Not a photo, not SVG sticks.
import { part as p0a } from './sakura-hang-narrow-p0a'
import { part as p0b } from './sakura-hang-narrow-p0b'
import { part as p1c } from './sakura-hang-narrow-p1c'
import { part as p1d } from './sakura-hang-narrow-p1d'
import { part as p1b } from './sakura-hang-narrow-p1b'
import { part as p2a1 } from './sakura-hang-narrow-p2a1'
import { part as p2a2 } from './sakura-hang-narrow-p2a2'
import { part as p2b1 } from './sakura-hang-narrow-p2b1'
import { part as p2b2 } from './sakura-hang-narrow-p2b2'
import { part as p3a1 } from './sakura-hang-narrow-p3a1'
import { part as p3a2 } from './sakura-hang-narrow-p3a2'
import { part as p3b1 } from './sakura-hang-narrow-p3b1'
import { part as p3b2 } from './sakura-hang-narrow-p3b2'
import { part as p4a1 } from './sakura-hang-narrow-p4a1'
import { part as p4a2 } from './sakura-hang-narrow-p4a2'
import { part as p4b1 } from './sakura-hang-narrow-p4b1'
import { part as p4b2 } from './sakura-hang-narrow-p4b2'
import { part as p5a1 } from './sakura-hang-narrow-p5a1'
import { part as p5a2 } from './sakura-hang-narrow-p5a2'
import { part as p5b1 } from './sakura-hang-narrow-p5b1'
import { part as p5b2 } from './sakura-hang-narrow-p5b2'
import { part as p6a1 } from './sakura-hang-narrow-p6a1'
import { part as p6a2 } from './sakura-hang-narrow-p6a2'
import { part as p6b1 } from './sakura-hang-narrow-p6b1'
import { part as p6b2 } from './sakura-hang-narrow-p6b2'
import { part as p7a1 } from './sakura-hang-narrow-p7a1'
import { part as p7a2 } from './sakura-hang-narrow-p7a2'
import { part as p7b1 } from './sakura-hang-narrow-p7b1'
import { part as p7b2 } from './sakura-hang-narrow-p7b2'
const src = 'data:image/jpeg;base64,' + p0a + p0b + p1c + p1d + p1b + p2a1 + p2a2 + p2b1 + p2b2 + p3a1 + p3a2 + p3b1 + p3b2 + p4a1 + p4a2 + p4b1 + p4b2 + p5a1 + p5a2 + p5b1 + p5b2 + p6a1 + p6a2 + p6b1 + p6b2 + p7a1 + p7a2 + p7b1 + p7b2
export default src
